[package]
name = "iitpp-roblox/vr-bottom-bar"
repository = "https://github.com/IITPP-Roblox/VR-Bottom-Bar"
description = "Provides a second bar below Roblox's VR bottom bar for custom buttons."
license = "MIT"
authors = ["IITPP-Roblox"]
version = "1.1.0"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
TopbarPlus = "1foreverhd/topbarplus@3.3.1"